# Generated by Django 4.1.7 on 2023-08-17 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0002_alter_warehouse_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to=settings.AUTH_USER_MODEL),
        ),
    ]
