# Generated by Django 4.2.7 on 2023-12-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0003_alter_warehouse_worker'),
        ('bid', '0001_initial'),
        ('objects', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectproductbase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_products_base', to='products.templateproduct'),
        ),
        migrations.AddField(
            model_name='bidtowarehouse',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidInWarehouses', to='bid.bid'),
        ),
        migrations.AddField(
            model_name='bidtowarehouse',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidsToWarehouse', to='objects.object'),
        ),
        migrations.AddField(
            model_name='bidtowarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidsToWarehouse', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='bidproducttowarehouse',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bid.bidtowarehouse'),
        ),
        migrations.AddField(
            model_name='bidproducttowarehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.templateproduct'),
        ),
        migrations.AddField(
            model_name='bidproduct',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bid.bid'),
        ),
        migrations.AddField(
            model_name='bidproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.templateproduct'),
        ),
        migrations.AddField(
            model_name='bid',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='objects.object'),
        ),
    ]
