# Generated by Django 4.1.7 on 2023-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_bid_bidproduct_delete_bidtom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
