# Generated by Django 4.1.7 on 2023-09-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('warehouses', '0003_alter_warehouse_worker'),
        ('products', '0013_templateproduct_status'),
        ('bid', '0003_bid_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='objects.object'),
        ),
        migrations.CreateModel(
            name='BidToWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidsToWarehouse', to='objects.object')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidsToWarehouse', to='warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='BidProductToWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bid.bidtowarehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.templateproduct')),
            ],
        ),
    ]
