# Generated by Django 4.1.7 on 2023-09-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_alter_bid_object_bidtowarehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtowarehouse',
            name='status',
            field=models.CharField(default='yuborilgan', max_length=244),
        ),
    ]
