# Generated by Django 4.1.7 on 2023-09-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0006_alter_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidtowarehouse',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidInWarehouses', to='bid.bid'),
        ),
        migrations.CreateModel(
            name='ObjectProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('price', models.CharField(blank=True, max_length=155, null=True)),
                ('total_price', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_products', to='bid.bid')),
            ],
        ),
    ]
