# Generated by Django 4.1.7 on 2023-09-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_templateproduct_status'),
        ('objects', '0001_initial'),
        ('bid', '0008_objectproducts_object_objectproducts_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectProductBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('total_price', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_products_base', to='objects.object')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_products_base', to='products.templateproduct')),
            ],
        ),
    ]
