# Generated by Django 4.1.7 on 2023-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
