# Generated by Django 4.1.7 on 2023-08-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_alter_warehouse_worker'),
        ('products', '0011_alter_product_delivery_alter_product_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_base', to='products.templateproduct'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_base', to='warehouses.warehouse'),
        ),
    ]
