# Generated by Django 4.1.7 on 2023-08-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productbase_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateproduct',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
