# Generated by Django 4.2.5 on 2023-09-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productset_templateproduct_product_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateproduct',
            name='total_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
