# Generated by Django 4.2.5 on 2023-09-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_templateproduct_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productset',
            name='total_price',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='templateproduct',
            name='price',
            field=models.FloatField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='templateproduct',
            name='total_price',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
