# Generated by Django 4.2.5 on 2023-09-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_name_productset_productset_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateproduct',
            name='product_set',
        ),
        migrations.DeleteModel(
            name='ProductSet',
        ),
    ]
