# Generated by Django 4.2.5 on 2023-09-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productset_templateproduct_product_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateproduct',
            name='product_set',
        ),
        migrations.DeleteModel(
            name='ProductSet',
        ),
    ]
