# Generated by Django 4.2.5 on 2023-09-29 13:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productset_templateproduct_product_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productset',
            old_name='productset_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='productset',
            name='total_productset_price',
        ),
        migrations.RemoveField(
            model_name='templateproduct',
            name='product_set',
        ),
        migrations.AddField(
            model_name='productset',
            name='data_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='productset',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
