# Generated by Django 4.2.5 on 2023-09-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_productset_name_productset_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productset',
            old_name='object',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='productset',
            name='name',
        ),
    ]
