# Generated by Django 4.2.3 on 2023-09-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_productset_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSet',
        ),
    ]
