# Generated by Django 4.2.3 on 2023-09-30 13:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('products', '0026_productset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productset',
            name='data_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='productset',
            name='object_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.object'),
        ),
    ]
