# Generated by Django 4.2.3 on 2023-09-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('products', '0027_alter_productset_data_array_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productset',
            name='object_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productset', to='objects.object'),
        ),
    ]
